# Esteban Perez-Hidalgo
# 880416-0631
# Dorian Valverde-Baspineiro
# 881010-T934

CC = gcc
COBJ = testsum0 testsum1 testsum2 testsum3 testsums testsumg

all : $(COBJ) time 

time : $(COBJ)
	./script.sh

testsum0 : HPC_A1_Task01_Time.c
	$(CC) -O0 -o testsum0 HPC_A1_Task01_Time.c
